# Generated by Django 5.0.6 on 2024-10-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycenterapp', '0002_division_subdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='branditem',
            name='categories',
            field=models.ManyToManyField(related_name='brand_items', to='beautycenterapp.category'),
        ),
        migrations.AddField(
            model_name='branditem',
            name='divisions',
            field=models.ManyToManyField(related_name='brand_items', to='beautycenterapp.division'),
        ),
        migrations.AddField(
            model_name='branditem',
            name='subdivisions',
            field=models.ManyToManyField(related_name='brand_items', to='beautycenterapp.subdivision'),
        ),
    ]
