# Generated by Django 5.0.6 on 2024-10-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycenterapp', '0003_branditem_categories_branditem_divisions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitems',
            name='brand_items',
            field=models.ManyToManyField(related_name='products', to='beautycenterapp.branditem'),
        ),
    ]
