# Generated by Django 5.0.6 on 2024-10-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycenterapp', '0005_subcategory_productitems_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
