# Generated by Django 5.0.6 on 2024-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycenterapp', '0006_category_is_hidden_subcategory_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='branditem',
            name='subcategories',
            field=models.ManyToManyField(related_name='brand_items', to='beautycenterapp.subcategory'),
        ),
    ]
