# Generated by Django 5.0.6 on 2024-10-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycenterapp', '0007_branditem_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='branditem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
