# Generated by Django 5.0.6 on 2024-10-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycenterapp', '0008_branditem_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitems',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
