# Generated by Django 5.0.6 on 2024-11-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycenterapp', '0010_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitems',
            name='sku',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
