# Generated by Django 5.0.6 on 2025-01-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycenterapp', '0012_productbulkuploadsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitems',
            name='rating',
            field=models.CharField(default='4.5', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productitems',
            name='rating_value',
            field=models.BigIntegerField(default=95, null=True),
        ),
        migrations.AlterField(
            model_name='productitems',
            name='vendor',
            field=models.CharField(default='Beauty Centre', max_length=100, null=True),
        ),
    ]
