# Generated by Django 5.0.6 on 2025-01-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycenterapp', '0013_alter_productitems_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branditem',
            name='sku',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
