# Generated by Django 5.0.6 on 2025-01-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycenterapp', '0014_branditem_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='DumpFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
