# Generated by Django 5.0.6 on 2025-01-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycenterapp', '0015_dumpfileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='branditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
    ]
