# Generated by Django 5.0.6 on 2025-02-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycenterapp', '0016_branditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitems',
            name='life_span',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productitems',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
