"""
Django settings for BeautyCenter project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u8!u03j6jswi3k@&hy+^@y4(pzn&0o5+p&*gey0zy015@fdz#h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'admin_tools_stats',  # this must be BEFORE 'admin_tools' and 'django.contrib.admin'
    'django_nvd3',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'beautycenterapp',
    'ckeditor',
    'ckeditor_uploader',
    'django_select2',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BeautyCenter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BeautyCenter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'beautycenter.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}



# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True
# MEDIA_ROOT = os.path.join(BASE_DIR,'media')
# MEDIA_URL = '/media/'
# STATIC_URL = os.path.join(BASE_DIR,'static')
# STATIC_URL = '/media/'

# Add these lines
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# STATIC_ROOT = os.path.join(BASE_DIR,"static")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Directory for file-based cache
CACHE_DIR = '/home/tt7ajtyot29j/BeautyCentre/tmp/django_caches'

# Check if the directory exists, if not, create it
if not os.path.exists(CACHE_DIR):
    os.makedirs(CACHE_DIR)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': CACHE_DIR,
    }
}


# Razorpay Secret keyccc
RAZORPAY_KEY_ID = 'rzp_test_z7C8WfvTtQGQqx'
RAZORPAY_KEY_SECRET = 'KtXb8JF5MSG60Iq71xKWGiju'

# Twilio account configuration
TWILIO_ACCOUNT_SID = 'ACa79e98452083e044ac8c31d9a713c562'
TWILIO_AUTH_TOKEN = '3445da9b67831647002e0c5b87a789a2'
TWILIO_WHATSAPP_NUMBER = 'whatsapp:+14155238886'
ADMIN_WHATSAPP_NUMBER = 'whatsapp:+917541869980'


# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Dashboard",
    "site_header": "Beauty Centre",
    "site_brand": "Dashboard",
    "welcome_sign": "Welcome to Dashboard",
    "copyright": "Beauty Centre",
    "search_model": "auth.User",
    
    # Customization
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "books"},
    ],
    
    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "/assets/imgs/theme/logo.jpeg",

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    
    # Customize UI elements
    "custom_css": "css/custom_admin.css",
    "custom_js": "js/custom_admin.js",
}



AUTH_USER_MODEL = 'beautycenterapp.CustomUser'

PLIVO_AUTH_ID="MAMJE3ODHHYMFJNJI1MD"
PLIVO_AUTH_TOKEN="OWFmNTI2YjMxMzUzMDA5YzMyZWZmNTg4MWE4ZjRh"
SENDER_PHONE_NUMBER="7463906582"